# This workflow tests the backend, then compiles the smart contract and outputs the 

name: Deploy to netlify

on: 
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16.10
      - run: yarn ci
      - run: yarn test:backend