plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

# Don't use plug and play and use node_modules instead
nodeLinker: node-modules 

# Don't hoist my node_modules in a single repo at the project root
nmHoistingLimits: "workspaces" 

# Not sure why this isn't the default and what the tradeoffs are here
checksumBehavior: update 